displayName: Request Logger
summary: Send request info to stdout.
type: middleware
import: github.com/joy2fun/traefik-plugin-log-request
testData:
  ResponseBody: false
  RequestIDHeaderName: X-Request-Id
